name: Test
on:
  workflow_dispatch:
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - run: |
          output="$(docker compose build challenges/${{ github.head_ref }}/ --dry-run 2>&1)"
          echo $output
